### ISSUE TITLE
automake/autoconf and other stuff

### ISSUE THREAD

**Issue by vtolstov** [jdarcy/etcd-api#8]
What do you think about atomake/autoconf stuff ?
Or this library positioned as embedded ?

**Comment by jdarcy** [comment]
Using autowhatever seems like a good idea in principle, but IMO it's overkill in this case.  Every time I have to deal with those things at work, it makes me want to quit programming altogether.  In that case the pain is justified, because there are significant platform differences to deal with.  In _this_ case that's not so.  Our two main dependencies are curl and yajl, which (as far as I know) present the same API on any platform they themselves support.  If there are other platform-specific differences, I'd rather deal with the first few via '#if defined(platform_constant)' until that becomes unwieldy.  A dozen of those would still be less cumbersome than even the most basic autobreak configuration.

**Comment by vtolstov** [comment]
Okay. Last question - how to fix breaking locking in current master? (with etcd 2.x) ?

**Comment by jdarcy** [comment]
There are various semi-standard recipes for this.  TTL/compare-and-swap/watches are generally involved, and the library supports all of those.  Some approaches involve in-order keys, which we don't support, but (since it just seems to be about using POST instead of PUT) it might not be hard to add.  Here are a couple of examples - in Go, but shouldn't be that hard to translate the algorithms into C:

https://github.com/datawisesystems/etcd-lock
https://github.com/hayesgm/go-etcd-lock/tree/master/lock

If you can ensure that a key exists before anybody tries to take a lock on it (e.g. during initialization/configuration), a simple compare-and-swap should be sufficient.

**Comment by vtolstov** [comment]
Thanks, @jdarcy i'm already think about CAS, can you check #9

**Comment by vtolstov** [comment]
Also can you provide you indent config or something similar (i'm using emacs), because my indent change files =(.

**Comment by jdarcy** [comment]
I'm not sure what the specific emacs settings would be (been years since I used emacs much), but the rules are pretty simple and similar to other projects I work on:
- no tabs
- indents are eight spaces
- no lines longer than 80 columns
- opening brace _not_ on separate line (except function begin)
- always use braces for compound statements

I have other preferences, e.g. for indentation of "case" statements or continuation lines, but life's too short to get all wrapped up in such things.  As long as the code's intent and effect are clear, I'm probably not going to worry about stuff other than the items above.
